"""add sample_type and is_sealed

Revision ID: 111c21dfe414
Revises: 73db1fcd6056
Create Date: 2026-09-26 17:25:22.819130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111c21dfe414'
down_revision: Union[str, Sequence[str], None] = '73db1fcd6056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_records', sa.Column('test_kit_type', sa.String(length=50), nullable=True))
    op.add_column('test_records', sa.Column('sample_id', sa.String(length=100), nullable=True))
    op.add_column('test_records', sa.Column('sample_type', sa.String(length=50), nullable=True))
    op.add_column('test_records', sa.Column('is_sealed', sa.Boolean(), nullable=True))
    op.add_column('test_records', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_test_records_sample_id'), 'test_records', ['sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_records_sample_id'), table_name='test_records')
    op.drop_column('test_records', 'notes')
    op.drop_column('test_records', 'is_sealed')
    op.drop_column('test_records', 'sample_type')
    op.drop_column('test_records', 'sample_id')
    op.drop_column('test_records', 'test_kit_type')
    # ### end Alembic commands ###
