"""Initial

Revision ID: 73db1fcd6056
Revises: 
Create Date: 2026-09-18 14:49:55.469596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73db1fcd6056'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Enum('CONSTABLE', 'HEAD_CONSTABLE', 'SUB_INSPECTOR', 'INSPECTOR', 'DSP', 'SP', 'DIG', 'IG', name='officerrank'), nullable=False),
    sa.Column('role', sa.Enum('FIELD_OFFICER', 'STATION_HEAD', 'DISTRICT_ADMIN', 'NCB_ADMIN', name='officerrole'), nullable=True),
    sa.Column('station_code', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_officers_badge_id'), 'officers', ['badge_id'], unique=True)
    op.create_index(op.f('ix_officers_id'), 'officers', ['id'], unique=False)
    op.create_table('test_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('officer_badge_id', sa.String(length=20), nullable=False),
    sa.Column('officer_name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('test_result', sa.String(length=50), nullable=False),
    sa.Column('substance', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('station_code', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_records_district'), 'test_records', ['district'], unique=False)
    op.create_index(op.f('ix_test_records_id'), 'test_records', ['id'], unique=False)
    op.create_index(op.f('ix_test_records_officer_badge_id'), 'test_records', ['officer_badge_id'], unique=False)
    op.create_index(op.f('ix_test_records_record_hash'), 'test_records', ['record_hash'], unique=False)
    op.create_index(op.f('ix_test_records_record_id'), 'test_records', ['record_id'], unique=True)
    op.create_index(op.f('ix_test_records_station_code'), 'test_records', ['station_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_records_station_code'), table_name='test_records')
    op.drop_index(op.f('ix_test_records_record_id'), table_name='test_records')
    op.drop_index(op.f('ix_test_records_record_hash'), table_name='test_records')
    op.drop_index(op.f('ix_test_records_officer_badge_id'), table_name='test_records')
    op.drop_index(op.f('ix_test_records_id'), table_name='test_records')
    op.drop_index(op.f('ix_test_records_district'), table_name='test_records')
    op.drop_table('test_records')
    op.drop_index(op.f('ix_officers_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_badge_id'), table_name='officers')
    op.drop_table('officers')
    # ### end Alembic commands ###
